# Generated by Django 3.1.2 on 2020-11-11 04:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 11, 4, 36, 52, 648903, tzinfo=utc)),
        ),
    ]
