# Generated by Django 3.1.2 on 2020-11-11 04:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_auto_20201111_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 11, 4, 37, 40, 94183, tzinfo=utc)),
        ),
    ]
