# Generated by Django 3.1.2 on 2020-11-11 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_auto_20201111_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 11, 4, 38, 55, 585307, tzinfo=utc)),
        ),
    ]
