# Generated by Django 3.1.2 on 2020-11-11 04:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0005_auto_20201111_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 11, 4, 40, 43, 566849, tzinfo=utc)),
        ),
    ]
