# Generated by Django 2.2.17 on 2020-12-06 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_auto_20201111_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 6, 7, 12, 25, 726683, tzinfo=utc)),
        ),
    ]
