# Generated by Django 3.1.4 on 2020-12-19 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0008_auto_20201219_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 9, 23, 35, 286968, tzinfo=utc)),
        ),
    ]
